config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'objects/index'

  resources :buckets do
    resources :objects
  end

  resources :objects do
    get 'download', :on => :collection
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  def index
    @buckets = OSS.client.list_buckets
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/objects_controller.rb
class ObjectsController < ApplicationController
  def index
    @bucket_name = params[:bucket_id]
    @prefix = params[:prefix]
    @bucket = OSS.client.get_bucket(@bucket_name)
    @objects = @bucket.list_objects(:prefix => @prefix, :delimiter => '/')
  end

  def download
    puts ">>>>>>>>>>>>>>>>>>>>>>>"
    @bucket_name = params[:bucket_id]
    @bucket = OSS.client.get_bucket(@bucket_name)
    @object_name = params[:id]
    #@object = @bucket.get_object(@object_name, :file => '/home/zn/work')
    @object = @bucket.object_url(@object_name)
    puts "#{@object}>>>>>>>>>"
    send_file "http://pic4.nipic.com/20091217/3885730_124701000519_2.jpg" , :filename => "bbb.jpg", :type => "application/force-download", :x_sendfile=>true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
  def bucket_objects_path(bucket_name)
    "/buckets/#{bucket_name}/objects"
  end
end  

app/helpers/objects_helper.rb
module ObjectsHelper
  def with_prefix(prefix)
    "?prefix=#{prefix}"
  end
  def remove_prefix(key, prefix)
    key.sub(/^#{prefix}/, '')
  end
  def upper_dir(dir)
    dir.sub(/[^\/]+\/$/, '') if dir
  end
  def new_object_path(bucket_name, prefix = nil)
    "/buckets/#{bucket_name}/objects/new/#{with_prefix(prefix)}"
  end
  def objects_path(bucket_name, prefix = nil)
    "/buckets/#{bucket_name}/objects/#{with_prefix(prefix)}"
  end
end

app/views/buckets/index.html.erb
<h1>Buckets#index</h1>
<p>Find me in app/views/buckets/index.html.erb</p>
<h1>Buckets</h1>
<%= link_to 'test', test_objects_path %>
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>CreationTime</th>
  </tr>
  <% @buckets.each do |bucket| %>
  <tr>
    <td><%= link_to bucket.name, bucket_objects_path(bucket.name) %></td>
    <td><%= bucket.location %></td>
    <td><%= bucket.creation_time.localtime.to_s %></td>
  </tr>
  <% end %>
</table>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to 'bucket', buckets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ossdemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/objects/index.html.erb
<h1>Objects in <%= @bucket_name %></h1>
<p> <%= link_to 'Upload file', new_object_path(@bucket_name, @prefix) %></p>
<table class="table table-striped">
  <tr>
    <th>Key</th>
    <th>Type</th>
    <th>Size</th>
    <th>LastModified</th>
  </tr>
  <tr>
    <td><%= link_to '../', with_prefix(upper_dir(@prefix)) %></td>
    <td>download</td>
    <td>Directory</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <% @objects.each do |object| %>
  <tr>
    <% if object.is_a?(Aliyun::OSS::Object) %>
    <td><%= link_to remove_prefix(object.key, @prefix),
            @bucket.object_url(object.key) %></td>
    <td><%= link_to object.key,
      download_objects_path(:bucket_id => @bucket_name, :id => object.key), :remote => true, :class => "download-object" %></td>
    <td><%= object.type %></td>
    <td><%= number_to_human_size(object.size) %></td>
    <td><%= object.last_modified.localtime.to_s %></td>
    <% else  %>
    <td><%= link_to remove_prefix(object, @prefix), with_prefix(object) %></td>
    <td>Directory</td>
    <td>N/A</td>
    <td>N/A</td>
    <% end  %>
  </tr>
  <% end %>
</table>